//==========================================================
//
// Title:      Lab 3
// Course:     CSC 2111
// Lab Number: 3
// Author:     Mihir Patel
// Date:       2/14/2021
// Description:
//   Calculate and store the revenue generated by selling the juice bottles
//
//==========================================================
#include <cstdlib> // For several general-purpose functions
#include <fstream> // For file handling
#include <iomanip> // For formatted output
#include <iostream> // For cin, cout, and system
#include <string> // For string data type
using namespace std; // So "std::cout" may be abbreviated to "cout"

int main()
{
    // Declare variables and show outfile
    ofstream outfile;
    int numOfJuiceBottlesSold = 35;
    int costOfaJuiceBottle = 0.75;
    double revenue;

    outfile.open("sales.dat");
    outfile << setprecision(2);

    // Function
    revenue = numOfJuiceBottlesSold * costOfaJuiceBottle;

    // Display output
    outfile << "Number of Juice Bottles Sold: " << numOfJuiceBottlesSold << endl;
    outfile << "Cost of Juice Bottle: " << costOfaJuiceBottle << endl;
    outfile << "Revenue: " << revenue << endl;

    outfile.close();

    return 0;
}